---
title: "Main_RMD"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(colorspace)
library(priceR)
library(scales)
```

```{r read-data, include = FALSE}
knoedler <- read_csv("knoedler.csv") %>%
  filter(object_type == "Painting") %>%
  mutate(price_amount = as.numeric(price_amount))
```

```{r inflation-work}
knoedler_usd <- knoedler %>%
  filter(price_currency == "dollars") %>%
  mutate(price_amount = adjust_for_inflation(price_amount, sale_date_year, to_date = 2020, country = "US"))

knoedler_pounds <- knoedler %>%
  filter(price_currency == "pounds") %>%
  mutate(price_amount = adjust_for_inflation(price_amount, sale_date_year, to_date = 2020, country = "GB"))
```

```{r dimension-wrangling}
#step1 - remove everything that isn't a number, a slash, or an x|X
knoedler_dimensions_usd <- knoedler_usd %>%
  mutate(dims_cleaned = str_replace_all(dimensions, "\\[|\\]", "")) %>%
  filter(!is.na(dimensions)) %>%
  mutate(dim1 = str_split(dims_cleaned, "x|X", simplify = TRUE)[,1],
         dim2 = str_split(dims_cleaned, "x|X", simplify = TRUE)[,2]) %>%
  mutate(dim1 = str_replace_all(dim1, "\\d/\\d", ""),
         dim2 = str_replace_all(dim2, "\\d/\\d", "")) %>%
  mutate(dim1 = str_replace_all(dim1, "[:alpha:]|[:punct:]", ""),
         dim2 = str_replace_all(dim2, "[:alpha:]|[:punct:]", "")) %>%
  mutate(dim1 = as.numeric(str_extract(dim1, "\\d\\d\\d|\\d\\d|\\d")),
         dim2 = as.numeric(str_extract(dim2, "\\d\\d\\d|\\d\\d|\\d"))) %>%
  mutate(inches_squared = dim1 * dim2)
knoedler_dimensions_usd <- knoedler_dimensions_usd %>%
  mutate(price_per_sqin = price_amount/inches_squared)

knoedler_dimensions_pounds <- knoedler_pounds %>%
  mutate(dims_cleaned = str_replace_all(dimensions, "\\[|\\]", "")) %>%
  filter(!is.na(dimensions)) %>%
  mutate(dim1 = str_split(dims_cleaned, "x|X", simplify = TRUE)[,1],
         dim2 = str_split(dims_cleaned, "x|X", simplify = TRUE)[,2]) %>%
  mutate(dim1 = str_replace_all(dim1, "\\d/\\d", ""),
         dim2 = str_replace_all(dim2, "\\d/\\d", "")) %>%
  mutate(dim1 = str_replace_all(dim1, "[:alpha:]|[:punct:]", ""),
         dim2 = str_replace_all(dim2, "[:alpha:]|[:punct:]", "")) %>%
  mutate(dim1 = as.numeric(str_extract(dim1, "\\d\\d\\d|\\d\\d|\\d")),
         dim2 = as.numeric(str_extract(dim2, "\\d\\d\\d|\\d\\d|\\d"))) %>%
  mutate(inches_squared = dim1 * dim2)
knoedler_dimensions_pounds <- knoedler_dimensions_pounds %>%
  mutate(price_per_sqin = price_amount/inches_squared)
```


```{r yearplots, warning=FALSE}
years_and_average_prices <- knoedler_usd %>%
  filter(!is.na(sale_date_year), !is.na(price_amount)) %>%
  group_by(sale_date_year) %>%
  summarise(average_price = mean(price_amount))

average_price_by_year <- ggplot(data = years_and_average_prices) +
  geom_line(aes(x = sale_date_year, y = average_price)) +
  theme_classic() +
  labs(title = "Average Price of Paintings Sold by Year",
       x = "Year",
       y = "Price")
average_price_by_year

year_density <- ggplot(data = knoedler, aes(x = sale_date_year)) +
  scale_x_continuous(limits = c(1900, 1980)) +
  geom_density(fill = "gray") +
  theme_classic() +
  labs(title = "Sale Years of Paintings",
       subtitle = "Density plot of years of sale", x = "Year of Sale",
       y = "")
year_density
```

```{r price-histograms, warning=FALSE}
 price_histogram_logged <- knoedler_usd %>%
  ggplot(aes(x = price_amount, color = price_amount)) +
  geom_histogram(bins = 50, fill = "darkgreen") +
  scale_x_log10(label = comma) +
  labs(title = "Knoedler Painting Sale Prices",
       x = "Price in USD",
       y = "# of Sales") +
  theme_classic()

 price_histogram_nonlogged <- knoedler_usd %>%
  ggplot(aes(x = price_amount, color = price_amount)) +
  geom_histogram(bins = 50, fill = "darkgreen") +
  scale_x_continuous(limits = c(0, 250000),label = comma) +
  labs(title = "Knoedler Painting Sale Prices",
       x = "Price in USD",
       y = "# of Sales") +
  theme_classic()
price_histogram_logged
price_histogram_nonlogged
  
```





```{r plots2, warning=FALSE}
dims_scatterplot <- knoedler_dimensions_usd %>%
ggplot() +
  theme_classic() +
  geom_point(aes(x = dim1, y = dim2, size = price_amount, color = price_amount), alpha = .5) +
  scale_color_viridis_c(direction = -1, labels = c("$50,000","$100,000","$200,000","$400,000","$600,000"), breaks = c(50000, 100000, 200000, 400000, 600000), begin = 0, end = 1) +
  scale_size_continuous(labels = c("$50,000", "$100,000","$200,000","$400,000","$600,000"), breaks = c(50000 ,100000, 200000, 400000, 600000)) +
  geom_abline(slope = 1.6, intercept = 0, color = "black", size = 1, linetype = 2) +
  geom_abline(slope = 1/1.6, intercept = 0, color = "black", size = 1, linetype = 2) +
  coord_cartesian(xlim = c(0, 175),
                  ylim = c(0, 175)) +
  guides(color = guide_legend(), size = guide_legend()) +
  labs(title = "Painting Dimensions and Sale Price",
       x = "Length in Inches",
       y = "Width in Inches",
       color = "Price in Dollars",
       size = "Price in Dollars",
       caption = "The Golden Ratio is denoted by the dotted lines")

subject_size_boxplots <- knoedler_dimensions_usd %>%
  filter(!is.na(subject)) %>%
ggplot() +
  geom_boxplot(aes(x = inches_squared, y = fct_reorder(subject, inches_squared, .fun = median), color = subject)) +
  scale_x_log10() +
  theme_classic() +
  labs(title = "Size of Paintings by Subject",
       caption = "Painting Sizes & Subjects from M. Knoedler & Co. Stock Books",
       x = "Size in Inches Squared",
       y = "Subject") +
  scale_color_discrete_qualitative() +
  theme(legend.position = "none")

subject_price_bars<- knoedler_usd %>%
  filter(!is.na(subject), !is.na(price_amount)) %>%
  group_by(subject) %>%
  summarise(mean_price = mean(price_amount)) %>%
  ggplot(aes(y = fct_reorder(subject, mean_price), x = mean_price, fill = subject)) +
  theme_classic() +
  geom_col() +
  scale_x_sqrt(label = comma) +
  scale_fill_discrete_qualitative() +
  theme(legend.position = "none") +
  labs(title = "Mean Painting Sales Price by Subject", 
       x = "Mean Painting Price in USD",
       y = "Subject")

dims_scatterplot
subject_size_boxplots
subject_price_bars
```


```{r moreplots}
#golden ratio closeness vs sale price
#raw size vs price

golden_ratio_plot <- knoedler_dimensions_usd %>%
  mutate(ratio1 = dim1/dim2,
         ratio2 = dim2/dim1,
         bigratio = if_else(ratio1 >= ratio2, ratio1, ratio2),
         difference = abs(1.618 - bigratio)) %>%
  select(price_amount, difference) %>%
  filter(!is.na(price_amount)) %>%
  ggplot(aes(x = difference, y = price_amount)) +
  theme_classic() +
  geom_point(aes(color = difference)) +
  scale_color_continuous_sequential(palette = "ag_GrnYl") +
  scale_y_continuous(label = comma) +
  labs(title = "Golden Ratio Similarity versus Price",
       x = "Closeness to the Golden Ratio",
       y = "Price in USD",
       caption = "Smaller values are more golden") +
  theme(legend.position = "none")


frequency_subject_plot <- knoedler_dimensions_usd %>%
  filter(!is.na(subject)) %>%
  count(subject) %>%
  ggplot(aes(x = n, y = fct_reorder(subject, n), fill = n)) +
  geom_col() +
  scale_fill_continuous_qualitative() +
  theme_classic() +
  theme(legend.position = "none") +
  labs(x = "Frequency",
       y = "Subject",
       title = "Frequency of Knoedler Subjects",
       caption = "Data from M. Knoedler & Co Stockbooks") +
  geom_text(aes(x = n + 17, y = fct_reorder(subject, n), label = as.character(n)))
golden_ratio_plot
frequency_subject_plot
```

```{r price-square-inches}
price_square_inches<- ggplot(data = knoedler_dimensions_usd,
       aes(y = price_amount,
           x = inches_squared)) +
  geom_point() +
  theme_classic() +
  labs(title = "Square Inches vs Price",
       x = "Square Inches",
       y = "Price in USD")
price_square_inches

price_per_yearmeans <- knoedler_dimensions_usd %>%
  filter(!is.na(sale_date_year), !is.na(price_per_sqin)) %>%
  group_by(sale_date_year) %>%
  summarise(avg_price_per_sqin = mean(price_per_sqin))

price_per_sq <- ggplot(data = price_per_yearmeans,
                       aes(y = avg_price_per_sqin, x = sale_date_year)) +
  geom_line() +
  theme_classic() +
  labs(title = "Price per Square Inch by Year",
       subtitle = "Yearly means",
       x = "Year of Sale",
       y = "Price per sq in")
price_per_sq

sqin_density <- ggplot(data = knoedler_dimensions_usd) +
  geom_density(aes(x = price_per_sqin), fill = "darkgreen") +
  theme_classic() +
  labs(title = "Density Plot of Price per Sqin")
sqin_density
```


```{r linear-modeling}
basic_lm <- lm(price_amount ~ nationality_1 + sale_date_year + subject + genre + inches_squared,
             data = knoedler_dimensions_usd)
summary(basic_lm)
```


```{r savingfunctions, eval=FALSE}
png(filename = "plots/years_and_average_prices.png")
years_and_average_prices
dev.off()

png(filename = "plots/year_density.png")
year_density
dev.off()

png(filename = "plots/subject_size_boxplots.png")
subject_size_boxplots
dev.off()

png(filename = "plots/subject_price_bars.png")
subject_price_bars
dev.off()

png(filename = "plots/sqin_density.png")
sqin_density
dev.off()

png(filename = "plots/price_square_inches.png")
price_square_inches
dev.off()

png(filename = "plots/price_per_sq.png")
price_per_sq
dev.off()

png(filename = "plots/price_histogram_logged.png")
price_histogram_logged
dev.off()

png(filename = "plots/price_histogram_nonlogged.png")
price_histogram_nonlogged
dev.off()


```

```{r}
knoedler %>%
  count(price_currency)
```


